[package]
name = "vmk2rk"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
ccm = "0.5.0"
clap = { version = "4.5.42", features = ["derive"] }
crc = "3.3.0"
gpt = "4.1.0"
hex = "0.4.3"
itertools = "0.14.0"
sha2 = "0.10.9"
uuid = "1.18.0"
